services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./sushiapp:/sushiapp

    environment:
      - DB_HOST=database
      - DB_NAME=sushishop_db
      - DB_USER=sushiadmin_user
      - DB_PASS=832weifjdjj1

    command: >
     sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:16.3-alpine3.20
    environment:
      - POSTGRES_DB=sushishop_db
      - POSTGRES_USER=sushiadmin_user
      - POSTGRES_PASSWORD=832weifjdjj1