services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./sushiapp:/sushiapp

    environment:
      - DB_HOST=database
      - DB_NAME=${PDB_NAME}
      - DB_USER=${PDB_USER}
      - DB_PASS=${PDB_PASS}

    command: >
     sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:16.3-alpine3.20
    environment:
      - POSTGRES_DB=${PDB_NAME}
      - POSTGRES_USER=${PDB_USER}
      - POSTGRES_PASSWORD=${PDB_PASS}

  